tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-background": "#e2e2e8",
                "secondary-fixed-dim": "#66de8c",
                outline: "#8f8fa0",
                "primary-fixed-dim": "#bec2ff",
                "primary-fixed": "#e0e0ff",
                "surface-container-high": "#282a2f",
                "on-primary-container": "#fffdff",
                "secondary-fixed": "#83fba5",
                "inverse-on-surface": "#2e3035",
                "surface-tint": "#bec2ff",
                "surface-container-low": "#191c20",
                "tertiary-container": "#9a6d00",
                "on-tertiary-fixed-variant": "#5e4200",
                "on-primary-fixed-variant": "#222fc2",
                "surface-container-lowest": "#0c0e13",
                "on-surface": "#e2e2e8",
                "on-surface-variant": "#c6c5d7",
                secondary: "#66de8c",
                "on-secondary": "#003919",
                "on-primary": "#000da4",
                "on-error-container": "#ffdad6",
                "surface-dim": "#111318",
                "surface-container-highest": "#33353a",
                "inverse-surface": "#e2e2e8",
                "surface-bright": "#37393e",
                surface: "#111318",
                error: "#ffb4ab",
                "on-tertiary-fixed": "#271900",
                "secondary-container": "#23a55a",
                "on-primary-fixed": "#000569",
                "inverse-primary": "#3f4cda",
                "primary-container": "#5865f2",
                "on-secondary-container": "#003115",
                background: "#111318",
                "on-tertiary": "#422d00",
                "on-secondary-fixed": "#00210c",
                "tertiary-fixed-dim": "#fbbc3c",
                "outline-variant": "#454655",
                "on-tertiary-container": "#fffdff",
                "error-container": "#93000a",
                "surface-container": "#1d2024",
                "on-secondary-fixed-variant": "#005228",
                primary: "#bec2ff",
                "surface-variant": "#33353a",
                tertiary: "#fbbc3c",
                "tertiary-fixed": "#ffdea8",
                "on-error": "#690005",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                "space-base": "1rem",
                "space-2xs": "0.125rem",
                "col-time-header": "4.5rem",
                "space-sm": "0.5rem",
                "grid-gutter": "0.75rem",
                "space-xs": "0.25rem",
                "space-lg": "1.25rem",
                "space-xl": "1.5rem",
                "space-md": "0.75rem",
                "layout-margin-mobile": "0.75rem",
                "space-3xl": "3rem",
                "space-2xl": "2rem",
                "layout-margin-desktop": "1.5rem",
            },
            fontFamily: {
                "label-lg": ["Inter"],
                "label-sm": ["Inter"],
                "headline-sm": ["Inter"],
                "time-display": ["Inter"],
                "body-lg": ["Inter"],
                "body-sm": ["Inter"],
                "label-md": ["Inter"],
                "headline-xl": ["Inter"],
                "body-md": ["Inter"],
                "headline-lg": ["Inter"],
            },
            fontSize: {
                "label-lg": [
                    "13px",
                    { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" },
                ],
                "label-sm": [
                    "10px",
                    { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "700" },
                ],
                "headline-sm": [
                    "16px",
                    { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" },
                ],
                "time-display": [
                    "13px",
                    { lineHeight: "16px", letterSpacing: "-0.01em", fontWeight: "600" },
                ],
                "body-lg": [
                    "15px",
                    { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" },
                ],
                "body-sm": [
                    "12px",
                    { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" },
                ],
                "label-md": [
                    "11px",
                    { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" },
                ],
                "headline-xl": [
                    "28px",
                    { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
                ],
                "body-md": [
                    "13px",
                    { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" },
                ],
                "headline-lg": [
                    "22px",
                    { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" },
                ],
            },
        },
    },
};
